image_width: 1920
image_height: 1080
camera_name: arena_camera_node
camera_matrix:
  rows: 3
  cols: 3
  data: [ 1216.25923,     0.     ,   937.51771,
             0.     ,  1216.97647,   535.23329,
             0.     ,     0.     ,     1.     ]
camera_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.326572, 0.093450, -0.000037, -0.000100, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1.,  0.,  0.,
          0.,  1.,  0.,
          0.,  0.,  1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [  919.21368,     0.     ,   924.59335,     0.     ,
             0.     ,  1132.30725,   534.42898,     0.     ,
             0.     ,     0.     ,     1.     ,     0.     ]
